# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 22:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilDeAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Aluno', verbose_name='Aluno')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Aluno',
                'managed': True,
                'verbose_name_plural': 'Perfis de Aluno',
            },
        ),
        migrations.CreateModel(
            name='PerfilDeVoluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Voluntario', verbose_name='Volunt\xe1rio')),
            ],
            options={
                'verbose_name': 'Perfil de Volunt\xe1rio',
                'managed': True,
                'verbose_name_plural': 'Perfis de Volunt\xe1rio',
            },
        ),
    ]
