# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildealuno',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='perfildevoluntario',
            name='voluntario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Voluntario', verbose_name='Volunt\xe1rio'),
        ),
    ]
