# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 20:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='N\xfamero')),
                ('title', models.CharField(max_length=200, verbose_name='T\xedtulo')),
                ('body', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Descri\xe7\xe3o')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Encerrado')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Data de encerramento')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Data de cria\xe7\xe3o')),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('D\xfavida', 'question'), ('Reclama\xe7\xe3o', 'complaint'), ('Bug (falha imprevista)', 'bug'), ('Melhoramento', 'enhancement'), ('Sugest\xe3o de novidade', 'feature'), ('Baixa prioridade', 'low priority'), ('M\xe9dia prioridade', 'medium priority'), ('Alta prioridade', 'high priority'), ('Duplicata', 'duplicate'), ('Sem validade', 'invalid'), ('Sem conserto', 'wontfix')], max_length=30, verbose_name='Etiqueta'), size=None)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Responsavel', to='website.Voluntario', verbose_name='Respons\xe1vel')),
            ],
            options={
                'verbose_name': 'Ticket',
                'managed': True,
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Data alvo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('is_open', models.BooleanField(verbose_name='Aberto')),
                ('last_updated', models.DateField(blank=True, null=True, verbose_name='\xdaltima atualiza\xe7\xe3o')),
            ],
            options={
                'verbose_name': 'Atualiza\xe7\xe3o',
                'managed': True,
                'verbose_name_plural': 'Atualiza\xe7\xf5es',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Milestone', verbose_name='Vers\xe3o alvo'),
        ),
        migrations.AddField(
            model_name='issue',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Autor', to='website.Voluntario', verbose_name='Autor'),
        ),
    ]
