# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:14
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'managed': True, 'verbose_name': 'Protocolo', 'verbose_name_plural': 'Protocolos'},
        ),
        migrations.AlterField(
            model_name='issue',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de cria\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('D\xfavida', 'question'), ('Reclama\xe7\xe3o', 'complaint'), ('Bug (falha imprevista)', 'bug'), ('Melhoramento', 'enhancement'), ('Sugest\xe3o de novidade', 'feature'), ('Baixa prioridade', 'low priority'), ('M\xe9dia prioridade', 'medium priority'), ('Alta prioridade', 'high priority'), ('Duplicata', 'duplicate'), ('Sem validade', 'invalid'), ('Sem conserto', 'wontfix')], max_length=30, null=True, verbose_name='Etiqueta'), size=None),
        ),
        migrations.AlterField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.Milestone', verbose_name='Vers\xe3o alvo'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Autor', to='website.Voluntario', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Aberto'),
        ),
    ]
