# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 23:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.IntegerField()),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('blog', models.CharField(blank=True, max_length=100, null=True)),
                ('turma', models.CharField(blank=True, max_length=1, null=True)),
                ('lingua_estrangeira', models.CharField(default='Espanhol', max_length=10)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('ano_letivo', models.DateField(default=2017)),
            ],
            options={
                'ordering': ('nome',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uerj_peso_1', models.CharField(blank=True, max_length=30, null=True)),
                ('uerj_peso_2', models.CharField(blank=True, max_length=30, null=True)),
                ('ufrj_mat_peso', models.IntegerField()),
                ('ufrj_lin_peso', models.IntegerField()),
                ('ufrj_nat_peso', models.IntegerField()),
                ('ufrj_hum_peso', models.IntegerField()),
                ('ufrj_red_peso', models.IntegerField()),
            ],
            options={
                'ordering': ('nome',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ementa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('ano_letivo', models.DateField(default=2017)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('disciplina',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('is_gestao', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('nome',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('num',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.IntegerField()),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('blog', models.CharField(blank=True, max_length=100, null=True)),
                ('graduacao_concluida', models.BooleanField(default=False)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('chegada', models.DateField(default=datetime.date.today)),
                ('equipe', models.ManyToManyField(to='website.Equipe')),
                ('graduacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Curso')),
                ('telefone', models.ManyToManyField(to='website.Telefone')),
            ],
            options={
                'ordering': ('nome',),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to='website.Voluntario'),
        ),
        migrations.AddField(
            model_name='ementa',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Equipe'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso_pretendido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Curso'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.ManyToManyField(to='website.Telefone'),
        ),
    ]
