# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 22:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.BigIntegerField(verbose_name='CPF')),
                ('data_de_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endere\xe7o')),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amap\xe1'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Esp\xedrito Santo'), ('GO', 'Goi\xe1s'), ('MA', 'Maranh\xe3o'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Par\xe1'), ('PB', 'Para\xedba'), ('PR', 'Paran\xe1'), ('PE', 'Pernambuco'), ('PI', 'Piau\xed'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rond\xf4nia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'S\xe3o Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='RJ', max_length=2)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('blog', models.CharField(blank=True, max_length=100, null=True)),
                ('turma', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='A', max_length=1, null=True)),
                ('lingua_estrangeira', models.CharField(choices=[('Espanhol', 'Espanhol'), ('Ingl\xeas', 'Ingl\xeas'), ('Franc\xeas', 'Franc\xeas (obs: n\xe3o possu\xedmos professor no momento)')], default='Espanhol', max_length=10, verbose_name='L\xedngua Estrangeira')),
                ('obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xf5es')),
                ('ano_letivo', models.IntegerField(default=2017, verbose_name='Ano letivo')),
                ('data_de_inscricao', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data de Inscri\xe7\xe3o')),
            ],
            options={
                'ordering': ('nome',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome', 'sobrenome'],
                'get_latest_by': 'name',
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uerj_peso_1', models.CharField(blank=True, max_length=30, null=True, verbose_name='UERJ Peso 1')),
                ('uerj_peso_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='UERJ Peso 2')),
                ('ufrj_mat_peso', models.IntegerField(blank=True, null=True, verbose_name='UFRJ Peso Matem\xe1tica')),
                ('ufrj_lin_peso', models.IntegerField(blank=True, null=True, verbose_name='UFRJ Peso Linguagens')),
                ('ufrj_nat_peso', models.IntegerField(blank=True, null=True, verbose_name='UFRJ Peso Natureza')),
                ('ufrj_hum_peso', models.IntegerField(blank=True, null=True, verbose_name='UFRJ Peso Humanidades')),
                ('ufrj_red_peso', models.IntegerField(blank=True, null=True, verbose_name='UFRJ Peso Reda\xe7\xe3o')),
            ],
            options={
                'ordering': ('nome',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
                'get_latest_by': 'nome',
            },
        ),
        migrations.CreateModel(
            name='Ementa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('ano_letivo', models.IntegerField(default=2017, verbose_name='Ano letivo')),
                ('obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xf5es')),
            ],
            options={
                'ordering': ('disciplina',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmprestimoParaAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_emprestimo', models.DateField(default=datetime.date.today, verbose_name='Empr\xe9stimo')),
                ('data_de_devolucao', models.DateField(default=website.models.default_timedelta, verbose_name='Devolu\xe7\xe3o')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Aluno')),
            ],
            options={
                'verbose_name': 'Empr\xe9stimo para Alunos',
                'verbose_name_plural': 'Empr\xe9stimos para Alunos',
            },
        ),
        migrations.CreateModel(
            name='EmprestimoParaVoluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_emprestimo', models.DateField(default=datetime.date.today, verbose_name='Empr\xe9stimo')),
                ('data_de_devolucao', models.DateField(default=website.models.default_timedelta, verbose_name='Devolu\xe7\xe3o')),
            ],
            options={
                'verbose_name': 'Empr\xe9stimo para Volunt\xe1rios',
                'verbose_name_plural': 'Empr\xe9stimos para Volunt\xe1rios',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('is_gestao', models.BooleanField(default=False, verbose_name='Gest\xe3o')),
            ],
            options={
                'ordering': ('nome',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('ano_de_publicacao', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano de Publica\xe7\xe3o')),
                ('data_de_aquisicao', models.DateField(default=datetime.date.today, verbose_name='Data de Aquisi\xe7\xe3o')),
                ('is_disponivel', models.BooleanField(default=True, verbose_name='Dispon\xedvel')),
                ('autor', models.ManyToManyField(to='website.Autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Editora')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=30, verbose_name='N\xfamero')),
            ],
            options={
                'ordering': ('num',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.BigIntegerField(verbose_name='CPF')),
                ('data_de_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endere\xe7o')),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amap\xe1'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Esp\xedrito Santo'), ('GO', 'Goi\xe1s'), ('MA', 'Maranh\xe3o'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Par\xe1'), ('PB', 'Para\xedba'), ('PR', 'Paran\xe1'), ('PE', 'Pernambuco'), ('PI', 'Piau\xed'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rond\xf4nia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'S\xe3o Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='RJ', max_length=2)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('blog', models.CharField(blank=True, max_length=100, null=True)),
                ('graduacao_concluida', models.BooleanField(default=False, verbose_name='Conclu\xedda')),
                ('obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xf5es')),
                ('chegada', models.DateField(blank=True, null=True)),
                ('is_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('equipe', models.ManyToManyField(to='website.Equipe')),
                ('graduacao', models.ManyToManyField(to='website.Curso', verbose_name='Gradua\xe7\xe3o')),
                ('telefone', models.ManyToManyField(default=(1435,), to='website.Telefone')),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'Volunt\xe1rio',
                'managed': True,
                'verbose_name_plural': 'Volunt\xe1rios',
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to='website.Voluntario'),
        ),
        migrations.AddField(
            model_name='emprestimoparavoluntario',
            name='emprestado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimoparavoluntario_related', to='website.Voluntario'),
        ),
        migrations.AddField(
            model_name='emprestimoparavoluntario',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Livro'),
        ),
        migrations.AddField(
            model_name='emprestimoparavoluntario',
            name='voluntario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Voluntario', verbose_name='Volunt\xe1rio'),
        ),
        migrations.AddField(
            model_name='emprestimoparaaluno',
            name='emprestado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimoparaaluno_related', to='website.Voluntario'),
        ),
        migrations.AddField(
            model_name='emprestimoparaaluno',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Livro'),
        ),
        migrations.AddField(
            model_name='ementa',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Equipe'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso_pretendido',
            field=models.ManyToManyField(blank=True, to='website.Curso', verbose_name='Curso Pretendido'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.ManyToManyField(default=(1435,), to='website.Telefone'),
        ),
    ]
