# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 01:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome', 'sobrenome'],
                'get_latest_by': 'name',
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
                'get_latest_by': 'nome',
            },
        ),
        migrations.CreateModel(
            name='EmprestimoParaAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_emprestimo', models.DateField(default=datetime.date.today)),
                ('data_de_devolucao', models.DateField(default=website.models.default_timedelta)),
            ],
            options={
                'verbose_name': 'Empr\xe9stimo para Alunos',
                'verbose_name_plural': 'Empr\xe9stimos para Alunos',
            },
        ),
        migrations.CreateModel(
            name='EmprestimoParaVoluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_emprestimo', models.DateField(default=datetime.date.today)),
                ('data_de_devolucao', models.DateField(default=website.models.default_timedelta)),
            ],
            options={
                'verbose_name': 'Empr\xe9stimo para Volunt\xe1rios',
                'verbose_name_plural': 'Empr\xe9stimos para Volunt\xe1rios',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('data_de_aquisicao', models.DateField(default=datetime.date.today)),
                ('is_disponivel', models.BooleanField(default=True)),
                ('autor', models.ManyToManyField(to='website.Autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Editora')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.AlterModelOptions(
            name='voluntario',
            options={'managed': False, 'ordering': ('nome',), 'verbose_name': 'Volunt\xe1rio', 'verbose_name_plural': 'Volunt\xe1rios'},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ano_letivo',
            field=models.IntegerField(default=2017),
        ),
        migrations.AddField(
            model_name='emprestimoparavoluntario',
            name='emprestado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimoparavoluntario_related', to='website.Voluntario'),
        ),
        migrations.AddField(
            model_name='emprestimoparavoluntario',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Livro'),
        ),
        migrations.AddField(
            model_name='emprestimoparavoluntario',
            name='voluntario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Voluntario'),
        ),
        migrations.AddField(
            model_name='emprestimoparaaluno',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Aluno'),
        ),
        migrations.AddField(
            model_name='emprestimoparaaluno',
            name='emprestado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimoparaaluno_related', to='website.Voluntario'),
        ),
        migrations.AddField(
            model_name='emprestimoparaaluno',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Livro'),
        ),
    ]
