# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170131_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ano_de_publicacao',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
