# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170206_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='ementa',
            name='disciplina',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='website.Equipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipe',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to='website.Voluntario'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='equipe',
            field=models.ManyToManyField(to='website.Equipe'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='graduacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Curso'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='is_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='telefone',
            field=models.ManyToManyField(to='website.Telefone'),
        ),
    ]
