# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170206_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'managed': True, 'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': True, 'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='ementa',
            options={'managed': True, 'ordering': ('disciplina',)},
        ),
        migrations.AlterModelOptions(
            name='equipe',
            options={'managed': True, 'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='voluntario',
            options={'managed': True, 'ordering': ('nome',), 'verbose_name': 'Volunt\xe1rio', 'verbose_name_plural': 'Volunt\xe1rios'},
        ),
    ]
