# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170213_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano_letivo',
            field=models.IntegerField(default=2017, verbose_name='Ano letivo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cep',
            field=models.IntegerField(verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.BigIntegerField(verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso_pretendido',
            field=models.ManyToManyField(blank=True, to='website.Curso', verbose_name='Curso Pretendido'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_de_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='Endere\xe7o'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='lingua_estrangeira',
            field=models.CharField(choices=[('Espanhol', 'Espanhol'), ('Ingl\xeas', 'Ingl\xeas'), ('Franc\xeas', 'Franc\xeas (obs: n\xe3o possu\xedmos professor no momento)')], default='Espanhol', max_length=10, verbose_name='L\xedngua Estrangeira'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='obs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xf5es'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='uerj_peso_1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='UERJ Peso 1'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='uerj_peso_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='UERJ Peso 2'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ufrj_hum_peso',
            field=models.IntegerField(blank=True, null=True, verbose_name='UFRJ Peso Humanidades'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ufrj_lin_peso',
            field=models.IntegerField(blank=True, null=True, verbose_name='UFRJ Peso Linguagens'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ufrj_mat_peso',
            field=models.IntegerField(blank=True, null=True, verbose_name='UFRJ Peso Matem\xe1tica'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ufrj_nat_peso',
            field=models.IntegerField(blank=True, null=True, verbose_name='UFRJ Peso Natureza'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ufrj_red_peso',
            field=models.IntegerField(blank=True, null=True, verbose_name='UFRJ Peso Reda\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='ementa',
            name='ano_letivo',
            field=models.IntegerField(default=2017, verbose_name='Ano letivo'),
        ),
        migrations.AlterField(
            model_name='ementa',
            name='obs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xf5es'),
        ),
        migrations.AlterField(
            model_name='emprestimoparaaluno',
            name='data_de_devolucao',
            field=models.DateField(default=website.models.default_timedelta, verbose_name='Devolu\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='emprestimoparaaluno',
            name='data_de_emprestimo',
            field=models.DateField(default=datetime.date.today, verbose_name='Empr\xe9stimo'),
        ),
        migrations.AlterField(
            model_name='emprestimoparavoluntario',
            name='data_de_devolucao',
            field=models.DateField(default=website.models.default_timedelta, verbose_name='Devolu\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='emprestimoparavoluntario',
            name='data_de_emprestimo',
            field=models.DateField(default=datetime.date.today, verbose_name='Empr\xe9stimo'),
        ),
        migrations.AlterField(
            model_name='emprestimoparavoluntario',
            name='voluntario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Voluntario', verbose_name='Volunt\xe1rio'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='is_gestao',
            field=models.BooleanField(default=False, verbose_name='Gest\xe3o'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano_de_publicacao',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano de Publica\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_de_aquisicao',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Aquisi\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='is_disponivel',
            field=models.BooleanField(default=True, verbose_name='Dispon\xedvel'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='num',
            field=models.CharField(max_length=30, verbose_name='N\xfamero'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='cep',
            field=models.IntegerField(verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='cpf',
            field=models.BigIntegerField(verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='data_de_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='Endere\xe7o'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='graduacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Curso', verbose_name='Gradua\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='graduacao_concluida',
            field=models.BooleanField(default=False, verbose_name='Conclu\xedda'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='is_ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='obs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xf5es'),
        ),
    ]
