# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170215_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='graduacao',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='graduacao',
            field=models.ManyToManyField(to='website.Curso', verbose_name='Gradua\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='telefone',
            field=models.ManyToManyField(default=(1435,), to='website.Telefone'),
        ),
    ]
