# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170313_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimoparaaluno',
            options={'verbose_name': 'Empr\xe9stimo para Aluno', 'verbose_name_plural': 'Empr\xe9stimos para Alunos'},
        ),
        migrations.AlterModelOptions(
            name='emprestimoparavoluntario',
            options={'verbose_name': 'Empr\xe9stimo para Volunt\xe1rio', 'verbose_name_plural': 'Empr\xe9stimos para Volunt\xe1rios'},
        ),
        migrations.AddField(
            model_name='livro',
            name='idioma',
            field=models.CharField(choices=[('Espanhol', 'Espanhol'), ('Franc\xeas', 'Franc\xeas'), ('Ingl\xeas', 'Ingl\xeas'), ('Portugu\xeas', 'Portugu\xeas'), ('Outro', 'Outro')], default='Portugu\xeas', max_length=30),
        ),
    ]
