# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170314_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimoparaaluno',
            name='devolvido',
            field=models.BooleanField(default=False, verbose_name='Devolvido'),
        ),
        migrations.AddField(
            model_name='emprestimoparavoluntario',
            name='devolvido',
            field=models.BooleanField(default=False, verbose_name='Devolvido'),
        ),
    ]
