# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20170314_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='tel',
            field=models.CharField(blank=True, default='(21) ', max_length=100, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, default='97885', max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='tel',
            field=models.CharField(blank=True, default='(21) ', max_length=100, null=True, verbose_name='Telefone'),
        ),
    ]
