# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_aluno_is_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cederj_especifica1',
            field=models.IntegerField(blank=True, null=True, verbose_name='CEDERJ Espec\xedfica 1'),
        ),
        migrations.AddField(
            model_name='curso',
            name='cederj_especifica2',
            field=models.IntegerField(blank=True, null=True, verbose_name='CEDERJ Espec\xedfica 2'),
        ),
    ]
