# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import projeto_redacao.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorDeRedacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Voluntario')),
            ],
            options={
                'verbose_name': 'Professor de Reda\xe7\xe3o',
                'managed': True,
                'verbose_name_plural': 'Professores de Reda\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Redacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_devolvida', models.BooleanField(default=False, verbose_name='Foi devolvida?')),
                ('data_de_entrega', models.DateField(default=datetime.date.today, verbose_name='Data de entrega')),
                ('data_de_correcao', models.DateField(default=datetime.date.today, verbose_name='Data de corre\xe7\xe3o')),
                ('data_de_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de devolu\xe7\xe3o')),
                ('competencia1', models.FloatField(blank=True, null=True, verbose_name='Compet\xeancia 1')),
                ('competencia2', models.FloatField(blank=True, null=True, verbose_name='Compet\xeancia 2')),
                ('competencia3', models.FloatField(blank=True, null=True, verbose_name='Compet\xeancia 3')),
                ('competencia4', models.FloatField(blank=True, null=True, verbose_name='Compet\xeancia 4')),
                ('nota', models.FloatField(blank=True, null=True, verbose_name='Nota final')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Aluno')),
                ('corretor', models.ManyToManyField(to='projeto_redacao.ProfessorDeRedacao')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Reda\xe7\xe3o',
                'managed': True,
                'verbose_name_plural': 'Reda\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('titulo',),
                'verbose_name': 'Tema',
                'managed': True,
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.AddField(
            model_name='redacao',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_redacao.Tema'),
        ),
    ]
