# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_redacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professorderedacao',
            options={'managed': True, 'ordering': ('voluntario',), 'verbose_name': 'Professor de Reda\xe7\xe3o', 'verbose_name_plural': 'Professores de Reda\xe7\xe3o'},
        ),
        migrations.AlterModelOptions(
            name='redacao',
            options={'managed': True, 'ordering': ('data_de_entrega',), 'verbose_name': 'Reda\xe7\xe3o', 'verbose_name_plural': 'Reda\xe7\xf5es'},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={'managed': True, 'ordering': ('data',), 'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
    ]
