# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_redacao', '0002_auto_20170215_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='redacao',
            name='obs',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observa\xe7\xf5es'),
        ),
    ]
