# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_redacao', '0003_redacao_obs'),
    ]

    operations = [

    ]
