# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_redacao', '0005_tema_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='redacao',
            name='competencia5',
            field=models.FloatField(blank=True, null=True, verbose_name='Compet\xeancia 5'),
        ),

    ]
