# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 22:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0015_auto_20170328_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDeInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.BigIntegerField(verbose_name='CPF')),
                ('data_de_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endere\xe7o')),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amap\xe1'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Esp\xedrito Santo'), ('GO', 'Goi\xe1s'), ('MA', 'Maranh\xe3o'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Par\xe1'), ('PB', 'Para\xedba'), ('PR', 'Paran\xe1'), ('PE', 'Pernambuco'), ('PI', 'Piau\xed'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rond\xf4nia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'S\xe3o Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='RJ', max_length=2)),
                ('tel', models.CharField(default='(21) ', max_length=100, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('blog', models.CharField(blank=True, max_length=100, null=True)),
                ('lingua_estrangeira', models.CharField(choices=[('Espanhol', 'Espanhol'), ('Ingl\xeas', 'Ingl\xeas'), ('Franc\xeas', 'Franc\xeas (obs: n\xe3o possu\xedmos professor no momento)')], default='Espanhol', max_length=10, verbose_name='L\xedngua Estrangeira')),
                ('data_do_pedido', models.DateField(default=datetime.date.today, verbose_name='Data de Inscri\xe7\xe3o')),
                ('curso_pretendido', models.ManyToManyField(blank=True, to='website.Curso', verbose_name='Curso Pretendido')),
                ('telefone', models.ManyToManyField(default=(1435,), to='website.Telefone')),
            ],
            options={
                'ordering': ('nome',),
                'abstract': False,
                'managed': True,
            },
        ),
    ]
