# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170328_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodeinscricao',
            name='is_ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
