# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 23:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=2018, verbose_name='Ano do concurso')),
                ('cod', models.CharField(max_length=10, verbose_name='C\xf3digo')),
                ('universidade', models.CharField(choices=[('UERJ', 'UERJ'), ('UFRJ', 'UFRJ'), ('UFF', 'UFF'), ('CEDERJ', 'CEDERJ')], max_length=10, verbose_name='Institui\xe7\xe3o')),
            ],
            options={
                'verbose_name': 'C\xf3digo',
                'managed': True,
                'verbose_name_plural': 'C\xf3digos',
            },
        ),
        migrations.CreateModel(
            name='MembroDaFamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.BigIntegerField(verbose_name='CPF')),
                ('data_de_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endere\xe7o')),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amap\xe1'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Esp\xedrito Santo'), ('GO', 'Goi\xe1s'), ('MA', 'Maranh\xe3o'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Par\xe1'), ('PB', 'Para\xedba'), ('PR', 'Paran\xe1'), ('PE', 'Pernambuco'), ('PI', 'Piau\xed'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rond\xf4nia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'S\xe3o Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='RJ', max_length=2)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('blog', models.CharField(blank=True, max_length=100, null=True)),
                ('relacionamento', models.CharField(max_length=10, verbose_name='Relacionamento')),
                ('rg', models.CharField(blank=True, max_length=10, null=True, verbose_name='RG')),
                ('emissor_rg', models.CharField(blank=True, max_length=10, null=True, verbose_name='\xd3rg\xe3o Emissor')),
                ('data_rg', models.DateField(blank=True, null=True, verbose_name='Data de emiss\xe3o')),
                ('renda', models.IntegerField(verbose_name='Renda')),
                ('copia_cpf', models.FileField(blank=True, null=True, upload_to='', verbose_name='C\xf3pia do CPF')),
                ('copia_rg', models.FileField(blank=True, null=True, upload_to='', verbose_name='C\xf3pia do RG')),
                ('copia_ctps', models.FileField(blank=True, null=True, upload_to='', verbose_name='C\xf3pia da CTPS')),
                ('copia_cr', models.FileField(blank=True, null=True, upload_to='', verbose_name='C\xf3pia da CR')),
                ('typeof_rg', models.CharField(blank=True, choices=[('Identidade civil', 'ID civil'), ('Identidade militar', 'ID militar'), ('Carteira de motorista', 'CNH'), ('Carteira de habilita\xe7\xe3o profissional', 'CHP'), ('Outro', 'Outro')], max_length=10, null=True, verbose_name='Tipo de comprova\xe7\xe3o de renda')),
                ('typeof_cr', models.CharField(blank=True, choices=[('Contracheque', 'Contracheque'), ('Recibo de benef\xedcio social', 'Recibo de benef\xedcio social'), ('Declara\xe7\xe3o de pr\xf3prio punho', 'Declara\xe7\xe3o de pr\xf3prio punho'), ('Outra', 'Outra')], max_length=10, null=True, verbose_name='Tipo de comprova\xe7\xe3o de renda')),
                ('typeof_renda', models.CharField(blank=True, choices=[('Trabalho com carteira assinada', 'Carteira assinada'), ('Trabalho sem carteira assinada', 'Informal'), ('Trabalho aut\xf4nomo ou profissional liberal', 'Aut\xf4nomo'), ('Benef\xedcio social', 'Benef\xedcio social'), ('Bolsa de est\xe1gio ou inicia\xe7\xe3o', 'Bolsa'), ('Aposentadoria do INSS', 'INSS'), ('Aposentadoria ou previd\xeancia privada', 'Previd\xeancia privada'), ('Outra', 'Outra')], max_length=10, null=True, verbose_name='Tipo de fonte de renda')),
                ('has_cpf', models.BooleanField(default=False, verbose_name='CPF entregue')),
                ('has_rg', models.BooleanField(default=False, verbose_name='RG entregue')),
                ('has_ctps', models.BooleanField(default=False, verbose_name='CTPS entregue')),
                ('has_cr', models.BooleanField(default=False, verbose_name='Comprova\xe7\xe3o de renda')),
                ('telefone', models.ManyToManyField(default=(1435,), to='website.Telefone')),
            ],
            options={
                'verbose_name': 'Membro da fam\xedlia',
                'managed': True,
                'verbose_name_plural': 'Membros da fam\xedlia',
            },
        ),
        migrations.CreateModel(
            name='PedidoDeIsencaoUERJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.CharField(blank=True, max_length=10, null=True, verbose_name='RG')),
                ('emissor_rg', models.CharField(blank=True, max_length=10, null=True, verbose_name='\xd3rg\xe3o Emissor')),
                ('data_rg', models.DateField(blank=True, null=True, verbose_name='Data de emiss\xe3o')),
                ('renda', models.IntegerField()),
                ('status_em', models.CharField(choices=[('Concluinte', 'Concluinte em 2017'), ('Conclu\xeddo', 'Conclu\xeddo'), ('Outro', 'Outro')], default='Concluinte', max_length=10, verbose_name='Ensino m\xe9dio')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='', verbose_name='Certificado de conclus\xe3o do Ensino M\xe9dio')),
                ('copia_cpf', models.FileField(blank=True, null=True, upload_to='', verbose_name='C\xf3pia do CPF')),
                ('copia_rg', models.FileField(blank=True, null=True, upload_to='', verbose_name='C\xf3pia do RG')),
                ('copia_ctps', models.FileField(blank=True, null=True, upload_to='', verbose_name='C\xf3pia da CTPS')),
                ('copia_cr', models.FileField(blank=True, null=True, upload_to='', verbose_name='C\xf3pia da CR')),
                ('copia_residencia', models.FileField(blank=True, null=True, upload_to='', verbose_name='Comprovante de resid\xeancia')),
                ('typeof_rg', models.CharField(blank=True, choices=[('ID civil', 'Identidade civil'), ('ID militar', 'Identidade militar'), ('CNH', 'Carteira de motorista'), ('CHP', 'Carteira de habilita\xe7\xe3o profissional'), ('Outro', 'Outro')], max_length=10, null=True, verbose_name='Tipo de comprova\xe7\xe3o de renda')),
                ('typeof_cr', models.CharField(blank=True, choices=[('Contracheque', 'Contracheque'), ('Recibo de benef\xedcio social', 'Recibo de benef\xedcio social'), ('Declara\xe7\xe3o de pr\xf3prio punho', 'Declara\xe7\xe3o de pr\xf3prio punho'), ('Outra', 'Outra')], max_length=10, null=True, verbose_name='Tipo de comprova\xe7\xe3o de renda')),
                ('typeof_renda', models.CharField(blank=True, choices=[('Carteira assinada', 'Trabalho com carteira assinada'), ('Informal', 'Trabalho sem carteira assinada'), ('Aut\xf4nomo', 'Trabalho aut\xf4nomo ou profissional liberal'), ('Benef\xedcio social', 'Benef\xedcio social'), ('Bolsa', 'Bolsa de est\xe1gio ou inicia\xe7\xe3o'), ('INSS', 'Aposentadoria do INSS'), ('Previd\xeancia privada', 'Aposentadoria ou previd\xeancia privada'), ('Outra', 'Outra')], max_length=10, null=True, verbose_name='Tipo de fonte de renda')),
                ('typeof_residencia', models.CharField(blank=True, choices=[('Luz', 'Luz'), ('\xc1gua', '\xc1gua'), ('G\xe1s', 'G\xe1s'), ('Telefone', 'Telefone fixo ou internet fixa'), ('Celular', 'Telefone celular ou internet m\xf3vel'), ('TV por assinatura', 'TV'), ('Cart\xe3o de cr\xe9dito', 'Cart\xe3o de Cr\xe9dito'), ('Outra', 'Outra')], max_length=10, null=True, verbose_name='Tipo de fonte de renda')),
                ('has_cpf', models.BooleanField(default=False, verbose_name='CPF entregue')),
                ('has_rg', models.BooleanField(default=False, verbose_name='RG entregue')),
                ('has_ctps', models.BooleanField(default=False, verbose_name='CTPS entregue')),
                ('has_cr', models.BooleanField(default=False, verbose_name='Comprova\xe7\xe3o de renda')),
                ('obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observa\xe7\xf5es')),
                ('exame', models.CharField(choices=[('EQ1', '1\xba Exame de Qualifica\xe7\xe3o'), ('EQ2', '2\xba Exame de Qualifica\xe7\xe3o')], max_length=10, verbose_name='Exame')),
                ('concurso', models.IntegerField(default=2018, verbose_name='Ano do concurso')),
                ('data_de_submissao', models.DateField(default=datetime.date.today, verbose_name='Data de submiss\xe3o')),
                ('data_de_entrega', models.DateField(blank=True, null=True, verbose_name='Data de entrega')),
                ('resposta', models.NullBooleanField(verbose_name='Aprovado')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Aluno')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicas_afirmativas.Codigo', verbose_name='C\xf3digo UERJ')),
                ('membros', models.ManyToManyField(to='politicas_afirmativas.MembroDaFamilia', verbose_name='Parente')),
            ],
            options={
                'verbose_name': 'Pedido de Isen\xe7\xe3o de Taxa de Inscri\xe7\xe3o UERJ',
                'managed': True,
                'verbose_name_plural': 'Pedidos de Isen\xe7\xe3o de Taxa de Inscri\xe7\xe3o UERJ',
            },
        ),
    ]
