# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicas_afirmativas', '0002_auto_20170313_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrodafamilia',
            name='tel',
            field=models.CharField(blank=True, default='(21) ', max_length=100, null=True, verbose_name='Telefone'),
        ),
    ]
