# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicas_afirmativas', '0003_auto_20170324_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrodafamilia',
            name='tel',
            field=models.CharField(default='(21) ', max_length=100, verbose_name='Telefone'),
        ),
    ]
