# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDePresencaDeAlunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('aluno', models.ManyToManyField(to='website.Aluno')),
            ],
            options={
                'verbose_name': 'Lista de Presen\xe7a de Alunos',
                'managed': True,
                'verbose_name_plural': 'Listas de Presen\xe7a de Alunos',
            },
        ),
        migrations.CreateModel(
            name='ListaDePresencaDeVoluntarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('voluntario', models.ManyToManyField(to='website.Voluntario')),
            ],
            options={
                'verbose_name': 'Lista de Presen\xe7a de Volunt\xe1rios',
                'managed': True,
                'verbose_name_plural': 'Listas de Presen\xe7a de Volunt\xe1rios',
            },
        ),
    ]
