# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_frequencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadepresencadealunos',
            name='obs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observa\xe7\xf5es'),
        ),
        migrations.AddField(
            model_name='listadepresencadevoluntarios',
            name='obs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observa\xe7\xf5es'),
        ),
    ]
